#!/bin/bash

# Prompt for sudo password
read -sp "Enter your sudo password: " sudopass

# Export the password as an environment variable for Ansible
export ANSIBLE_LOCALHOST_WARNING=false
export ANSIBLE_BECOME_PASS=$sudopass

echo "Changing to the playbook directory..."
cd ./playbooks

echo "Installing system environment..."
ansible-playbook dotnet.yml
ansible-playbook dev-env.yml
ansible-playbook rust.yml
ansible-playbook lua.yml
ansible-playbook go.yml
ansible-playbook nvm.yml
ansible-playbook neovim.yml
ansible-playbook neovim-config.yml
ansible-playbook tmux.yml

unset ANSIBLE_BECOME_PASS

echo "______ _____ _   _ _____ _____ _   _  ___________ "
echo "|  ___|_   _| \ | |_   _/  ___| | | ||  ___|  _  \\"
echo "| |_    | | |  \| | | | \ \`--.| |_| || |__ | | | |"
echo "|  _|   | | | . \` | | |  \`--. \  _  ||  __|| | | |"
echo "| |    _| |_| |\  |_| |_/\__/ / | | || |___| |/ / "
echo "\_|    \___/\_| \_/\___/\____/\_| |_/\____/|___/  "
echo "______ _____ _____ _____  _   _                   "
echo "| ___ \_   _|_   _/  __ \| | | |                  "
echo "| |_/ / | |   | | | /  \/| |_| |                  "
echo "| ___ \ | |   | | | |    |  _  |                  "
echo "| |_/ /_| |_  | | | \__/\| | | |_ _ _             "
echo "\____/ \___/  \_/  \____/\_| |_(_|_|_)            "
echo "                                                  "
