#!/bin/bash
alias ga='git add'
alias gaa='git add --all'
alias gau='git add --update'
alias gb='git branch'
alias gba='git branch --all'
alias gbd='git branch --delete'
alias gc='git commit --verbose'
alias gca='git commit --verbose --all'
alias gcmsg='git commit --message'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcd='git  checkout $(git_develop_branch)'
alias gcm='git checkout $(git_main_branch)'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gfa='git fetch --all --tags --prune --jobs=10'
alias gfo='git fetch origin'
alias gl='git log --stat'
alias gm='git merge'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gpl='git pull'
alias ggp='git push origin $(git branch --show-current)'
alias gpf='git push --force-with-lease'
alias gst='git status'

# Enable Git autocomplete for aliases
if [ -f /usr/share/bash-completion/completions/git ]; then
    source /usr/share/bash-completion/completions/git
    
    __git_complete ga _git_add
    __git_complete gaa _git_add
    __git_complete gau _git_add
    __git_complete gb _git_branch
    __git_complete gba _git_branch
    __git_complete gbd _git_branch
    __git_complete gc _git_commit
    __git_complete gca _git_commit
    __git_complete gcmsg _git_commit
    __git_complete gco _git_checkout
    __git_complete gcob _git_checkout
    __git_complete gcd _git_checkout
    __git_complete gcm _git_checkout
    __git_complete gcp _git_cherry_pick
    __git_complete gcpa _git_cherry_pick
    __git_complete gcpc _git_cherry_pick
    __git_complete gd _git_diff
    __git_complete gds _git_diff
    __git_complete gf _git_fetch
    __git_complete gfa _git_fetch
    __git_complete gfo _git_fetch
    __git_complete gl _git_log
    __git_complete gm _git_merge
    __git_complete gma _git_merge
    __git_complete gmc _git_merge
    __git_complete gpl _git_pull
    __git_complete ggp _git_push
    __git_complete gpf _git_push
    __git_complete gst _git_status
fi
