#!/bin/bash

alias ga='git add'
alias gaa='git add --all'
alias gau='git add --update'

alias gb='git branch'
alias gba='git branch --all'
alias gbd='git branch --delete'

alias gc='git commit --verbose'
alias gca='git commit --verbose --all'
alias gcmsg='git commit --message'

alias gco='git checkout'
alias gcob='git checkout -b'
alias gcd='git  checkout $(git_develop_branch)'
alias gcm='git checkout $(git_main_branch)'

alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'

alias gd='git diff'
alias gds='git diff --staged'

alias gf='git fetch'
alias gfa='git fetch --all --tags --prune --jobs=10'
alias gfo='git fetch origin'

alias gl='git log --stat'

alias gm='git merge'
alias gma='git merge --abort'
alias gmc='git merge --continue'

alias gpl='git pull'

alias ggp='git push origin $(git branch --show-current)'
alias gpf='git push --force-with-lease'

alias gst='git status'
