- name: Setup Docker
  hosts: localhost
  become: true
  tasks:
    - name: Include main vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: "Install required software"
      ansible.builtin.apt:
        pkg:
          - git
          - docker
          - docker-compose
          - python3-pip
          - curl
          - cmake
          - gettext

    - name: Ensure group "docker" exists with correct gid
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: docker
        append: true
