- name: Install Microsoft Packages Repository
  hosts: localhost
  become: true

  tasks:
    - name: Download Microsoft signing key and repository
      get_url:
        url: "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
        dest: /tmp/packages-microsoft-prod.deb

    - name: Install Microsoft signing key and repository
      apt:
        deb: /tmp/packages-microsoft-prod.deb

    - name: Clean up
      file:
        path: /tmp/packages-microsoft-prod.deb
        state: absent

    - name: Update packages
      apt:
        update_cache: yes
