- name: Configure Git user
  hosts: localhost

  tasks:
    - name: Set Git user email
      git_config:
        name: user.email
        value: "wschwanke@gmail.com"
        scope: global

    - name: Set Git user name
      git_config:
        name: user.name
        value: "Will Schwanke"
        scope: global
