- hosts: localhost
  tasks:

  - name: Include main vars
    ansible.builtin.include_vars:
      file: vars.yml

  - name: "Install required software"
    become: true
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - lua5.1
      - liblua5.1-0-dev

  - name: stylua
    ansible.builtin.shell:
      cmd: cargo install stylua

  - name: Download LuaRocks tar.gz
    get_url:
      url: https://luarocks.org/releases/luarocks-3.11.0.tar.gz
      dest: /tmp/luarocks.tar.gz
      mode: '0644'  # Ensure the file has the correct permissions

  - name: Extract LuaRocks archive
    unarchive:
      src: /tmp/luarocks.tar.gz
      dest: /tmp/
      remote_src: yes
      creates: /tmp/luarocks-3.11.0  # This avoids re-extracting if the directory already exists

  - name: Install LuaRocks from source
    become: true
    shell: ./configure && make && make install
    args:
      chdir: /tmp/luarocks-3.11.0
      creates: /usr/local/bin/luarocks  # This avoids re-running if LuaRocks is already installed

  - name: luacheck
    become: true
    ansible.builtin.shell:
      cmd: luarocks install luacheck
