---
- name: Clone kickstart.nvim repository
  hosts: localhost
  tasks:
    - name: Ensure the ~/.config/nvim directory exists
      ansible.builtin.file:
        path: ~/.config/nvim
        state: directory
        mode: "0755"

    - name: Clone kickstart.nvim repository into ~/.config/nvim
      ansible.builtin.git:
        repo: "https://github.com/wschwanke/kickstart.nvim"
        dest: ~/.config/nvim
        version: master
        force: yes
