- hosts: localhost
  tasks:

  - name: Include main vars
    ansible.builtin.include_vars:
      file: vars.yml

  - name: Remove old versions of neovim
    become: true
    ansible.builtin.file:
       path: "{{ home }}/neovim"
       state: absent

  - name: Clone neovim
    ansible.builtin.git:
       repo: https://github.com/neovim/neovim.git
       dest: "{{ home }}/neovim"
       depth: 1
       version: stable

  - name: Neovim Make Install
    become: true
    ansible.builtin.command: sudo make install
    args:
      chdir: "{{ home }}/neovim"
