- name: Generate SSH Key for GitHub
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure SSH directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: "0700"

    - name: Generate SSH Key
      ansible.builtin.shell: ssh-keygen -t ed25519 -C "{{ email }}" -f ~/.ssh/github -N ''

    - name: Generate Azure DevOps SSH Key
      ansible.builtin.shell: ssh-keygen -t rsa-sha2-512 -f ~/.ssh/azure_devops -N ''

    - name: Print SSH Public Key
      ansible.builtin.command: cat ~/.ssh/github.pub
      register: ssh_key

    - name: Display SSH Public Key
      ansible.builtin.debug:
        msg: "{{ ssh_key.stdout }}"

    - name: Print SSH Public Key
      ansible.builtin.command: cat ~/.ssh/azure_devops.pub
      register: ssh_key

    - name: Display SSH Public Key
      ansible.builtin.debug:
        msg: "{{ ssh_key.stdout }}"
