- hosts: localhost
  tasks:
    - name: Include main vars
      ansible.builtin.include_vars:
        file: vars.yml

    - name: installing tmux
      become: true
      apt:
        name: tmux
        state: present
        update_cache: yes
