- name: Install Zsh and Oh My Zsh
  hosts: localhost
  become: yes
  tasks:
    - name: Install Zsh
      package:
        name: zsh
        state: present

    - name: Set Zsh as default shell
      ansible.builtin.command: chsh -s /bin/zsh "{{ ansible_user_id }}"

    - name: Install Oh My Zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: Set Zsh theme (optional)
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="agnoster"'
        backup: yes
