- name: Install Zsh and Oh My Zsh
  hosts: localhost
  become: true
  tasks:
    - name: Install Zsh
      become: true
      ansible.builtin.apt:
        pkg:
          - zsh

    - name: Set Zsh as default shell
      ansible.builtin.command: chsh -s /bin/zsh "{{ ansible_user_id }}"

    - name: Install Oh My Zsh
      ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: Install Gruvbox
      ansible.builtin.shell: curl -L https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme > ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme
