- name: Install Zsh and Oh My Zsh
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Install Zsh
      become: true
      ansible.builtin.apt:
        pkg:
          - zsh

    - name: Set Zsh as default shell
      become: true
      ansible.builtin.command:
        cmd: chsh -s /bin/zsh "{{ username }}"

    - name: Install Oh My Zsh
      ansible.builtin.shell: |
        if [ ! -d "{{ ansible_env.HOME }}/.oh-my-zsh" ]; then
          sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        fi
      args:
        executable: /bin/zsh

    - name: Install Gruvbox
      ansible.builtin.shell: |
        curl -L https://raw.githubusercontent.com/sbugzu/gruvbox-zsh/master/gruvbox.zsh-theme > ~/.oh-my-zsh/custom/themes/gruvbox.zsh-theme
      args:
        executable: /bin/zsh
