- name: Install Zsh and Oh My Zsh
  hosts: localhost
  vars_files:
    - vars.yml
  tasks:
    - name: Install Zsh
      become: true
      ansible.builtin.apt:
        pkg:
          - zsh

    - name: Set Zsh as default shell
      become: true
      ansible.builtin.command:
        cmd: chsh -s /bin/zsh "{{ username }}"

