[env]
TERM = xterm-256color


[font]
size = 14

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[font.bold]
family = "SauceCodePro Nerd Font Mono"

[font.italic]
family = "SauceCodePro Nerd Font Mono"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"

[window]

[window.dimensions]
columns = 150
lines = 48

[scrolling]
history = 50000
